name: Example Harness Deploy
on:
  push:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: harness-deploy-action
        id: harness-deploy-action
        uses: ./
        with:
          webhookUrl: ${{ secrets.HARNESS_WEBHOOK_URL }}
          application: XYZ12345678ABC
          services: web,console,job
          version: ${{ github.sha }}

      - name: output
        run: |
          echo harness_url: ${{ steps.harness-deploy-action.outputs.harness_url }}
