name: "Run Test and Package Latest JS"

on:
  push:
    branches:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn test

  check-latest-dist:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run prepare
      name: Compile javascript into the dist folder with ncc
    - name: Check latest code is packaged in the dist folder
      id: check-for-changes
      run: |
        if [ "$(git status --porcelain | wc -l)" -eq 0 ]
        then
          echo "::set-output name=CHANGES_TO_COMMIT::false"
        else
          echo "::group::Git diff to commit"
          git diff
          echo "::endgroup::"

          echo "::set-output name=CHANGES_TO_COMMIT::true"
        fi

    - if: ${{ steps.check-for-changes.outputs.CHANGES_TO_COMMIT == 'true' }}
      run: |
        echo "run yarn install && yarn prepare locally and commit the updates from the dist folder"
        exit 1

    - if: ${{ steps.check-for-changes.outputs.CHANGES_TO_COMMIT == 'false' }}
      name: No changes to commit
      run: echo no changes to commit
